"""Generated documentation helpers."""

from __future__ import annotations

from collections import defaultdict


def generate_skills_catalog(registry: dict) -> str:
    skills = registry["skills"]
    by_domain: dict[str, list[dict]] = defaultdict(list)
    for skill in skills:
        by_domain[skill["category"]].append(skill)

    lines = [
        "# Skills Catalog",
        "",
        "This file is generated by `python3 scripts/generate_docs.py`.",
        "",
        f"- Skill count: {registry['skill_count']}",
        "",
        "## Domains",
        "",
    ]

    for domain, domain_skills in sorted(by_domain.items()):
        lines.extend(
            [
                f"### {domain}",
                "",
                "| Skill | Tags | Outputs | Official Sources |",
                "|-------|------|---------|------------------|",
            ]
        )
        for skill in sorted(domain_skills, key=lambda item: item["name"]):
            tags = ", ".join(skill["tags"][:5])
            outputs = ", ".join(skill["outputs"][:3])
            sources = "; ".join(skill["official_sources"][:2]) or "—"
            lines.append(
                f"| `{skill['name']}` | {tags} | {outputs} | {sources} |"
            )
        lines.append("")

    example = next((item for item in skills if item["id"] == "apex/soql-security"), None)
    if example:
        lines.extend(
            [
                "## Example Walkthrough",
                "",
                "Example real skill: `apex/soql-security`",
                "",
                f"- Location: `{example['file_location']}`",
                f"- Inputs: {', '.join(example['inputs']) or '—'}",
                f"- Outputs: {', '.join(example['outputs']) or '—'}",
                f"- Search seed: `python3 scripts/search_knowledge.py \"with user mode stripinaccessible\" --domain apex`",
                "",
            ]
        )

    return "\n".join(lines).rstrip() + "\n"
